from common import enum

class State(enum.Enum):
    # U.S. States
    AL = enum.Item('AL', 'Alabama', oldabbrev = 'Ala.')
    AK = enum.Item('AK', 'Alaska', oldabbrev = 'Alaska')
    AZ = enum.Item('AZ', 'Arizona', oldabbrev = 'Ariz.')
    AR = enum.Item('AR', 'Arkansas', oldabbrev = 'Ark.')
    CA = enum.Item('CA', 'California', oldabbrev = 'Calif.')
    CO = enum.Item('CO', 'Colorado', oldabbrev = 'Colo.')
    CT = enum.Item('CT', 'Connecticut', oldabbrev = 'Conn.')
    DE = enum.Item('DE', 'Delaware', oldabbrev = 'Del.')
    DC = enum.Item('DC', 'District of Columbia', oldabbrev = 'D.C.')
    FL = enum.Item('FL', 'Florida', oldabbrev = 'Fla.')
    GA = enum.Item('GA', 'Georgia', oldabbrev = 'Ga.')
    HI = enum.Item('HI', 'Hawaii', oldabbrev = 'Hawaii')
    ID = enum.Item('ID', 'Idaho', oldabbrev = 'Idaho')
    IL = enum.Item('IL', 'Illinois', oldabbrev = 'Ill.')
    IN = enum.Item('IN', 'Indiana', oldabbrev = 'Ind.')
    IA = enum.Item('IA', 'Iowa', oldabbrev = 'Iowa')
    KS = enum.Item('KS', 'Kansas', oldabbrev = 'Kan.')
    KY = enum.Item('KY', 'Kentucky', oldabbrev = 'Ky.')
    LA = enum.Item('LA', 'Louisiana', oldabbrev = 'La.')
    ME = enum.Item('ME', 'Maine', oldabbrev = 'Maine')
    MD = enum.Item('MD', 'Maryland', oldabbrev = 'Md.')
    MA = enum.Item('MA', 'Massachusetts', oldabbrev = 'Mass.')
    MI = enum.Item('MI', 'Michigan', oldabbrev = 'Mich.')
    MN = enum.Item('MN', 'Minnesota', oldabbrev = 'Minn.')
    MS = enum.Item('MS', 'Mississippi', oldabbrev = 'Miss.')
    MO = enum.Item('MO', 'Missouri', oldabbrev = 'Mo.')
    MT = enum.Item('MT', 'Montana', oldabbrev = 'Mont.')
    NE = enum.Item('NE', 'Nebraska', oldabbrev = 'Neb.')
    NV = enum.Item('NV', 'Nevada', oldabbrev = 'Nev.')
    NH = enum.Item('NH', 'New Hampshire', oldabbrev = 'N.H.')
    NJ = enum.Item('NJ', 'New Jersey', oldabbrev = 'N.J.')
    NM = enum.Item('NM', 'New Mexico', oldabbrev = 'N.M.')
    NY = enum.Item('NY', 'New York', oldabbrev = 'N.Y.')
    NC = enum.Item('NC', 'North Carolina', oldabbrev = 'N.C.')
    ND = enum.Item('ND', 'North Dakota', oldabbrev = 'N.D.')
    OH = enum.Item('OH', 'Ohio', oldabbrev = 'Ohio')
    OK = enum.Item('OK', 'Oklahoma', oldabbrev = 'Okla.')
    OR = enum.Item('OR', 'Oregon', oldabbrev = 'Ore.')
    PA = enum.Item('PA', 'Pennsylvania', oldabbrev = 'Pa.')
    RI = enum.Item('RI', 'Rhode Island', oldabbrev = 'R.I.')
    SC = enum.Item('SC', 'South Carolina', oldabbrev = 'S.C.')
    SD = enum.Item('SD', 'South Dakota', oldabbrev = 'S.D.')
    TN = enum.Item('TN', 'Tennessee', oldabbrev = 'Tenn.')
    TX = enum.Item('TX', 'Texas', oldabbrev = 'Texas')
    UT = enum.Item('UT', 'Utah', oldabbrev = 'Utah')
    VT = enum.Item('VT', 'Vermont', oldabbrev = 'Vt.')
    VA = enum.Item('VA', 'Virginia', oldabbrev = 'Va.')
    WA = enum.Item('WA', 'Washington', oldabbrev = 'Wash.')
    WV = enum.Item('WV', 'West Virginia', oldabbrev = 'W.Va.')
    WI = enum.Item('WI', 'Wisconsin', oldabbrev = 'Wis.')
    WY = enum.Item('WY', 'Wyoming', oldabbrev = 'Wyo.')

    # Other
    AS = enum.Item('AS', 'American Samoa', oldabbrev = 'A.S.')
    GU = enum.Item('GU', 'Guam', oldabbrev = 'Guam')
    MP = enum.Item('MP', 'Northern Mariana Islands', oldabbrev = 'M.P.')
    PR = enum.Item('PR', 'Puerto Rico', oldabbrev = 'P.R.')
    VI = enum.Item('VI', 'Virgin Islands', oldabbrev = 'V.I.')
    DK = enum.Item('DK', 'Dakota Territory', oldabbrev='')
    PI = enum.Item('PI', 'Philippines Territory/Commonwealth', oldabbrev='')
    OL = enum.Item('OL', 'Territory of Orleans', oldabbrev='')