"""
Django settings for accessible_eats project.

Generated by 'django-admin startproject' using Django 1.8.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import socket

development_environs = ['Kunals-MacBook-Pro.local']

if socket.gethostname() in development_environs:
    production = False
else:
    production = True

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')s9e9!xztnd^*vcps0b7*3mt1gjs-tt4qor5oyn4k^#xn7vi7='

# SECURITY WARNING: don't run with debug turned on in production!
if production:
    DEBUG = False
    TEMPLATE_DEBUG = False
    ADMINS = (
        ('Kunal Mehta', 'accessible.eats@gmail.com'),
    )
    SERVER_EMAIL = 'accessible.eats@gmail.com'
else:
    DEBUG = True

ALLOWED_HOSTS = [
    'ae-dev2.us-west-2.elasticbeanstalk.com',
    'www.accessible-eats.com',
    'localhost',
    '127.0.0.1',
]


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accessible_eats_app',
    'storages',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'accessible_eats.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'accessible_eats.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

if 'RDS_DB_NAME' in os.environ:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': os.environ['RDS_DB_NAME'],
            'USER': os.environ['RDS_USERNAME'],
            'PASSWORD': os.environ['RDS_PASSWORD'],
            'HOST': os.environ['RDS_HOSTNAME'],
            'PORT': os.environ['RDS_PORT'],
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

EMAIL_BACKEND = 'django_smtp_ssl.SSLEmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'email-smtp.us-west-2.amazonaws.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'AKIAIZ2HGRDUZH62SELA'
EMAIL_HOST_PASSWORD = 'AmLPVUiDm5i2315/5GnsYimNxFQJg/wTYs4TYUtzl0oh'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'


if not production:
    MEDIA_ROOT = os.path.join(BASE_DIR, '..', 'accessible_eats_app', 'media')
    MEDIA_URL = '/media/'
else:
    MEDIA_ROOT = os.path.join(BASE_DIR, '..', 'media')
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto.S3BotoStorage'
    AWS_S3_SECURE_URLS = False
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_ACCESS_KEY_ID = 'AKIAI5IZRA6FUUBN4KRA'
    AWS_S3_SECRET_ACCESS_KEY = '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'
    AWS_STORAGE_BUCKET_NAME = 'accessible-eats-media'
    AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME
    MEDIA_URL = "https://%s/" % AWS_S3_CUSTOM_DOMAIN

if not production:
    CURRENT_HOST = 'http://127.0.0.1:8000/'
else:
    CURRENT_HOST = 'http://www.accessible-eats.com/'

GOOGLE_API_KEY = 'AIzaSyDnAkO8M2ykT71YBC0WmSfmZtEUhnoCN50'

YELP_CONSUMER_KEY = 'US2mtMpskJ36JSb_n6Uy-w'
YELP_CONSUMER_SECRET = 'gtu09XfGR3FwC_Ar7LLYGEB-3EM'
YELP_TOKEN = 'fIvJ3B48nF_Ro6QP5C-m6ptJOQHB5p7u'
YELP_TOKEN_SECRET = '8lApWweZlez8vmlBYQ5mNMW3pWI'

